### ISSUE TITLE
Who owns Routingnumbers.info 

### ISSUE THREAD

**Issue by aakash-stockpile** [mattpolito/routing_numbers#1]
Hi!

I'd like to use Routingnumbers.info in production, but I don't know how valid the information would be. I can't find any information on when it is updated or how long it will be kept up.

**Comment by mattpolito** [comment]
@aakash-stockpile I honestly don't know. When I built the wrapper for it, the site was purely information. It did not have all of the ads on it.

The data appears to be coming from federal reserve data but I have no idea how often it is updated.

Use at your own risk I will say. Same as any API.

**Comment by aakash-stockpile** [comment]
Thanks! I'll just write a parser for the FedACH file myself, then.
